CREATE DATABASE task_api_db;

CREATE TABLE taskuserroles(
	role_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	role_title varchar(30) NOT NULL UNIQUE
);


CREATE TABLE taskuser(
	user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name varchar(500) NOT NULL UNIQUE,
	user_email varchar(500) NOT NULL UNIQUE,
	user_passHash varchar(1000) NOT NULL,
	password_change_time timestamp NOT NULL,
	user_phone_number varchar(200),
	user_role int REFERENCES taskuserroles(role_id)
	);

insert into taskuserroles(role_title) values('ROLE_ADMIN');
insert into taskuserroles(role_title) values('ROLE_USER');
