---
# dataSource configs
spring:
  datasource:
    username: admin
    password: admin1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_api_db
  output:
    ansi:
      console-available: true
  application:
    name: task-api

  # Hibernate configs
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: 'true'
  # in order to allow HTTP methods PUT, PATCH, DELETE
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'


application:
  api:
    hash:
      salt: ${SALT}
    otp:
      validTime: '31536000000'
    encryption: ${ENCRYPTION_KEY}
  jwt_secret: ${JWT_SECRET}

logging:
  level:
    ROOT: DEBUG
    io.task.api.app: INFO

server:
  port: 8443
  ssl:
    key-store: file:../keystore.jks
    key-store-password: ${KEY_STORE_PASSWORD:test1test}
    key-password: ${KEY_PASSWORD:test1test}
    enabled: true
  tomcat:
    keep-alive-timeout: 1000 # This is the time in milliseconds that the Tomcat server will wait for another HTTP request before closing the connection
    keep-alive-max-requests: 200 # This is the maximum number of HTTP requests that the Tomcat server will allow on a keep-alive connection before closing the connection
    use-keep-alive: true # This enables keep-alive connections

multithread:
  number: '8'
task:
  password: 'iY/tZsdC+rdC4Tt2klCnmfzE70jgHI6A'
  source: '/home/evgeny/PROJECTS/TaskApi/tests'
  recipient: 'tasks@usachev.fr'
